name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.29.1

      - name: Check format
        run: deno cache main.ts

      # TODO: add a build step here

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "avdoseferovic-healtcare"
          entrypoint: "./main.ts" # TODO: update entrypoint